export const subjects = [
  "maths",
  "language",
  "science",
  "history",
  "coding",
  "economics",
  "physics",
  "chemistry",
  "biology",
  "english",
  "geography",
  "literature",
  "philosophy",
  "psychology",
  "computer science",
  "data science",
  "art",
  "music",
  "business",
  "marketing",
  "finance",
  "entrepreneurship",
  "health",
  "politics",
  "sociology",
  "environment",
];

export const subjectsColors = {
  science: "#B4E50D",
  maths: "#00CAFF",
  language: "#BDE7FF",
  coding: "#FFC8E4",
  history: "#F8F8E1",
  economics: "#C8FFDF",
  physics: "#FFD580",
  chemistry: "#FF9AA2",
  biology: "#B5EAD7",
  english: "#E0BBE4",
  geography: "#FFDAC1",
  literature: "#CBAACB",
  philosophy: "#A2D2FF",
  psychology: "#FBC4AB",
  "computer science": "#A5FFD6",
  art: "#FFB3C6",
  music: "#C1FFD7",
  business: "#FFF5BA",
  marketing: "#FFCF9C",
  finance: "#C0ECCC",
  entrepreneurship: "#FFD1DC",
  health: "#B5EAEA",
  politics: "#FFABAB",
  sociology: "#F6EAC2",
  environment: "#B8E0D2",
};

export const voices = {
  male: { casual: "2BJW5coyhAzSr8STdHbE", formal: "c6SfcYrb2t09NHXiT80T" },
  female: { casual: "ZIlrSGI4jZqobxRKprJz", formal: "sarah" },
};

export const recentSessions = [
  {
    id: "1",
    subject: "science",
    name: "Neura the Brainy Explorer",
    topic: "Neural Network of the Brain",
    duration: 45,
    color: "#E5D0FF",
  },
  {
    id: "2",
    subject: "maths",
    name: "Countsy the Number Wizard",
    topic: "Derivatives & Integrals",
    duration: 30,
    color: "#FFDA6E",
  },
  {
    id: "3",
    subject: "language",
    name: "Verba the Vocabulary Builder",
    topic: "English Literature",
    duration: 30,
    color: "#BDE7FF",
  },
  {
    id: "4",
    subject: "coding",
    name: "Codey the Logic Hacker",
    topic: "Intro to If-Else Statements",
    duration: 45,
    color: "#FFC8E4",
  },
  {
    id: "5",
    subject: "history",
    name: "Memo, the Memory Keeper",
    topic: "World Wars: Causes & Consequences",
    duration: 15,
    color: "#FFECC8",
  },
  {
    id: "6",
    subject: "economics",
    name: "The Market Maestro",
    topic: "The Basics of Supply & Demand",
    duration: 10,
    color: "#C8FFDF",
  },
];
